//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2019ZH601_PRACTICA0204
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id { get; set; }
        public string producto1 { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public decimal precio { get; set; }
        public int idcategoria { get; set; }
        public Nullable<int> idcolor { get; set; }
        public Nullable<int> idtalla { get; set; }
    }
}
