//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2019ZH601_PRACTICA0204
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talla
    {
        public int id { get; set; }
        public string talla1 { get; set; }
        public string estado { get; set; }
    }
}
